// ══════════════════════════════════════════════════════════════
//  aspects-utility.js  —  Utility Legendary Aspects
// ══════════════════════════════════════════════════════════════
registerAspectCategory("utility", [
    { name: "Aspect of Anemia",                slots: [] },
    { name: "Aspect of Armageddon",            slots: [] },
    { name: "Aspect of Berserk Ripping",       slots: [] },
    { name: "Aspect of Control",               slots: [] },
    { name: "Aspect of Corruption",            slots: [] },
    { name: "Aspect of Encircling Blades",     slots: [] },
    { name: "Aspect of Explosive Verve",       slots: [] },
    { name: "Aspect of Grasping Veins",        slots: [] },
    { name: "Aspect of Mending Stone",         slots: [] },
    { name: "Aspect of Metamorphic Stone",     slots: [] },
    { name: "Aspect of Noxious Ice",           slots: [] },
    { name: "Aspect of Piercing Cold",         slots: [] },
    { name: "Aspect of Plunging Darkness",     slots: [] },
    { name: "Aspect of Retribution",           slots: [] },
    { name: "Aspect of Singed Extremities",    slots: [] },
    { name: "Aspect of Stolen Vigor",          slots: [] },
    { name: "Aspect of the Bounding Conduit",  slots: [] },
    { name: "Aspect of the Calm Breeze",       slots: [] },
    { name: "Aspect of the Caged Heart",       slots: [] },
    { name: "Aspect of the Changeling's Debt", slots: [] },
    { name: "Aspect of the Damned",            slots: [] },
    { name: "Aspect of the Frozen Tundra",     slots: [] },
    { name: "Aspect of the Protector",         slots: [] },
    { name: "Aspect of the Rampaging Werebeast", slots: [] },
    { name: "Aspect of the Relentless Armsmaster", slots: [] },
    { name: "Aspect of the Ursine Horror",     slots: [] },
    { name: "Aspect of Three Curses",          slots: [] },
    { name: "Aspect of Unstable Imbuements",   slots: [] },
    { name: "Bold Chieftain's Aspect",         slots: [] },
    { name: "Cheat's Aspect",                  slots: [] },
    { name: "Earthstriker's Aspect",           slots: [] },
    { name: "Encircling Blades Aspect",        slots: [] },
    { name: "Exploiter's Aspect",              slots: [] },
    { name: "Flamethrower's Aspect",           slots: [] },
    { name: "Healer's Aspect",                 slots: [] },
    { name: "Nighthowler's Aspect",            slots: [] },
    { name: "Protecting Aspect",               slots: [] },
    { name: "Smiting Aspect",                  slots: [] },
    { name: "Stormchaser's Aspect",            slots: [] },
    { name: "Unyielding Commander's Aspect",   slots: [] },
    { name: "Warding Key Aspect",              slots: [] }
]);
