// ══════════════════════════════════════════════════════════════
//  tempers-utility.js  —  Utility Temper Manuals
//  Valid slots: Helm, Chest, Pants, Gloves, Boots, Amulet, Offhand
//  Slots are universal — same for all classes
// ══════════════════════════════════════════════════════════════
registerTemperCategory("utility", {
    slots: ["helm", "chest", "pants", "gloves", "boots", "amulet", "offhand"],
    entries: [
        "Agility Charges",
        "Aura Duration",
        "Berserk Duration",
        "Berserk Uptime",
        "Companion Cooldown Reduction",
        "Concealment Duration",
        "Corpse Generation",
        "Crowd Control Duration",
        "Curse Duration",
        "Enchantment Bonus",
        "Freeze Duration",
        "Guardian Skill Ranks",
        "Lucky Hit Chance",
        "Lucky Hit Chance to Heal",
        "Lucky Hit Chance to Slow",
        "Lucky Hit Chance to Stun",
        "Ranks to Affliction Skills",
        "Ranks to Agility Skills",
        "Ranks to All Skills",
        "Ranks to Aura Skills",
        "Ranks to Blood Skills",
        "Ranks to Bone Skills",
        "Ranks to Brawling Skills",
        "Ranks to Centipede Skills",
        "Ranks to Companion Skills",
        "Ranks to Conjuration Skills",
        "Ranks to Conviction Skills",
        "Ranks to Core Skills",
        "Ranks to Cutthroat Skills",
        "Ranks to Dark Magic Skills",
        "Ranks to Defensive Skills",
        "Ranks to Eagle Skills",
        "Ranks to Gorilla Skills",
        "Ranks to Holy Skills",
        "Ranks to Imbuement Skills",
        "Ranks to Jaguar Skills",
        "Ranks to Macabre Skills",
        "Ranks to Marksman Skills",
        "Ranks to Nature Magic Skills",
        "Ranks to Pyromancy Skills",
        "Ranks to Shadow Skills",
        "Ranks to Shock Skills",
        "Ranks to Summoning Skills",
        "Ranks to Trap Skills",
        "Ranks to Warmth Skills",
        "Ranks to Weapon Mastery Skills",
        "Ranks to Wrath Skills",
        "Resolve Generation",
        "Shrine Buff Duration",
        "Skill Cooldown Reduction",
        "Slow Duration",
        "Spirit Hall Bonuses",
        "Stun Duration",
    ]
});