// ══════════════════════════════════════════════════════════════
//  aspects-utility.js  —  Utility Legendary Aspects
//  Source: D4 Wiki (all classes). classes:[] = all classes.
//  power: aspect description shown in tooltip/modal.
// ══════════════════════════════════════════════════════════════
registerAspectCategory("utility", [
    { name: "Aphotic Aspect", classes: ["necromancer", "rogue", "warlock"], power: "Shadow damage gains [20 - 30]%[x] increased Lucky Hit Chance." },
    { name: "Aspect of Accursed Touch", classes: [], power: "Lucky Hit: Up to a [30.0 - 40.0]% chance for your Skills to inflict Vampiric Curse on enemies. Enemies afflicted with Vampiric Curse are also Vulnerable.\n\nVampiric Curse's stored souls deal [40.0 - 60.0]% increased damage." },
    { name: "Aspect of Anemia", classes: ["barbarian"], power: "Lucky Hit: Damaging enemies affected by Damage over Time or Vulnerable enemies has up to a [20 - 30]% chance to Stun them for 2 seconds." },
    { name: "Aspect of Anger Management", classes: ["barbarian", "druid"], power: "While above 50 Primary Resource, deal [15.0 - 20.0]%[x] increased damage and gain Berserking, but lose 3 Primary Resource Regeneration." },
    { name: "Aspect of Apprehension", classes: ["spiritborn"], power: "Once an enemy is Slowed by at least 80%, they also become Feared for 3 seconds. You deal [30 - 40]%[x] increased damage to Feared enemies." },
    { name: "Aspect of Audacity", classes: [], power: "When there are at least 5 Close enemies, Stun them for [2.5 - 4.5] seconds. Can only occur once every 20 seconds." },
    { name: "Aspect of Biting Cold", classes: ["necromancer", "rogue", "sorcerer"], power: "Cold damage is increased by [15.0 - 20.0]% and makes enemies Vulnerable for 4 seconds." },
    { name: "Aspect of Booming Voice", classes: ["barbarian"], power: "Your Shout Skill effect durations are increased by [20 - 30]%[+] and Weaken enemies for 5 seconds." },
    { name: "Aspect of Cauterization", classes: ["warlock"], power: "Taking Direct Damage while you have Volatility has a 75% chance to either strike you for an additional 3% of your Maximum Life as Fire damage or Fortify you for [3.00 - 6.00]% of your Maximum Life." },
    { name: "Aspect of Concussive Blend", classes: ["rogue"], power: "Stun Grenades gain [30 - 45]%[+] increased Size and [60 - 90]%[+] increased Crowd Control Duration." },
    { name: "Aspect of Crippling Darkness", classes: ["necromancer", "rogue", "warlock"], power: "Lucky Hit: Shadow damage has up to a 15% chance to deal [20 - 30]%[x] increased damage, Fear and Immobilize for 1 second." },
    { name: "Aspect of Dazzling Light", classes: ["paladin"], power: "The first time you apply Judgement to an enemy, you Daze them for [1.0 - 3.0] seconds." },
    { name: "Aspect of Debilitating Darkness", classes: ["necromancer"], power: "Your Desecrated Ground deals [15 - 25]%[x] increased damage and makes enemies Vulnerable." },
    { name: "Aspect of Deeper Shadows", classes: ["warlock"], power: "Maximum Shadowform stacks increased by [2 - 6]." },
    { name: "Aspect of Dominance", classes: [], power: "Crowd Controlling an enemy grants [1 - 2] Resolve." },
    { name: "Aspect of Elusive Menace", classes: [], power: "Your Dodge Chance increases by [20 - 30]%[+] whenever you take damage. Successfully Dodging resets this bonus." },
    { name: "Aspect of Excellence", classes: ["paladin"], power: "Losing 0 Resolve grants [30 - 50]% increased Retribution chance for 10 seconds.\n\nRetribution gains 50%[+] increased Size." },
    { name: "Aspect of Explosive Verve (Utility)", classes: ["rogue"], power: "Your Grenade Skills count as Trap Skills. Whenever you arm a Trap or drop Grenades, you gain [10 - 30]%[+] increased Movement Speed for 3 seconds." },
    { name: "Aspect of Falling Feathers", classes: ["spiritborn"], power: "Moving with a Mobility Skill or Evade spawns Storm Feathers behind you.\n\nStorm Feathers now drop from the sky as they are spawned, each dealing [375 - 525] Lightning damage on impact." },
    { name: "Aspect of Fiendish Oppression", classes: ["warlock"], power: "Summoning a Greater Demon Knocks Down enemies around it for 5 seconds. Your Lesser Demon Skills deal [10 - 20]%[x] increased damage to Crowd Controlled enemies." },
    { name: "Aspect of Fortune", classes: [], power: "You gain [15.0 - 20.0]%[x] Lucky Hit Chance against Elite enemies." },
    { name: "Aspect of Grasping Whirlwind", classes: ["barbarian"], power: "Whirlwind Pulls enemies to you every [6.0 - 3.0] seconds." },
    { name: "Aspect of Hewed Flesh", classes: ["necromancer"], power: "Lucky Hit: Up to a 25% chance to form a Corpse at the target's location. Your Corpse Skills deal [15.0 - 20.0]%[x] increased damage." },
    { name: "Aspect of Immolation", classes: ["warlock"], power: "The duration of any Volatility or Demonform you gain is increased by [160 - 200]%[+] if you have the other." },
    { name: "Aspect of Interdiction", classes: ["necromancer", "paladin", "spiritborn"], power: "Gain [2.0 - 3.0]%[+] Block Chance per Resolve stack." },
    { name: "Aspect of Iron Rain (Utility)", classes: ["rogue"], power: "Your Arrow Storms deal [15.0 - 25.0]%[x] increased damage and continuously apply Vulnerable." },
    { name: "Aspect of Kinetic Suppression", classes: ["spiritborn"], power: "Casting a Non-Basic Mobility Skill grants 3 Resolve.\n\nCasting a Defensive Skill with 8 stacks of Resolve increases its damage by [100 - 150]%[x]." },
    { name: "Aspect of Malevolence", classes: ["warlock"], power: "You gain Overpower for each [30 - 10] Wrath you gain while at Maximum Wrath." },
    { name: "Aspect of Mending Obscurity", classes: ["rogue"], power: "When entering Stealth and every second while Stealthed, you Heal for [10.5 - 15.0]% of your Maximum Life. Breaking Stealth Fortifies you for [7.0 - 10.0]% of your Maximum Life." },
    { name: "Aspect of Mending Stone", classes: ["druid"], power: "Earth Skills Fortify you for [4.00 - 6.00]% of your Maximum Life when first dealing damage." },
    { name: "Aspect of Mind's Awakening", classes: ["sorcerer"], power: "Cast Skills grant a bonus based on their element:\n♦Pyromancy Immobilizes enemies for [1.0 - 2.0] seconds\n♦Shock grants [10 - 20]% bonus Movement Speed for 4 seconds\n♦Frost grants a Barrier for 1.0% of your Maximum Life for 4 seconds.\nIf you've dealt damage with each element in the last 4 seconds, Skills grant all bonuses regardless of their element." },
    { name: "Aspect of Misfortune", classes: ["warlock"], power: "Hexed enemies that try to attack you have a [15.0 - 30.0]% chance to instead be Knocked Down for 3 seconds." },
    { name: "Aspect of Natural Instincts", classes: ["druid"], power: "Each Druid form gains a bonus every [7.0 - 5.0] seconds:\n\nWolf 1 stack of Ferocity.\nBear 1 stack of Overpower.\nHuman 1 stack of Resolve." },
    { name: "Aspect of Piercing Cold", classes: ["necromancer", "rogue", "sorcerer"], power: "You apply [30.0 - 50.0]%[x] more Chill and deal 20%[x] increased damage to Chilled enemies." },
    { name: "Aspect of Poisonous Clouds (Utility)", classes: ["rogue"], power: "When entering Stealth, create a cloud that deals [900 - 1,170] Poison damage and Immobilizes enemies over 6 seconds." },
    { name: "Aspect of Potent Exchange", classes: ["spiritborn"], power: "Gain 1 Resolve when you Dodge an attack. Your Potency Skills consume 2 Resolve to deal [20 - 30]%[x] increased damage." },
    { name: "Aspect of Quickening Fog", classes: ["rogue"], power: "You automatically drop a Smoke Grenade at the end of Dash. Smoke Grenades reduce Dash's Cooldown by [0.50 - 0.70] seconds for each enemy hit, up to [1.50 - 2.10] seconds." },
    { name: "Aspect of Rallying Reversal", classes: [], power: "You have a [60 - 80]% chance to gain 1 Ferocity when you Crowd Control an enemy or apply any Stagger to a Boss." },
    { name: "Aspect of Reactive Armor", classes: ["spiritborn"], power: "Gain 10%[+] Block Chance.\nBlocking an attack from an enemy has a [30 - 70]% chance to invoke a free Concussive Stomp at them." },
    { name: "Aspect of Recalling Feathers", classes: ["spiritborn"], power: "Casting a Focus Skill recalls all Nearby Storm Feathers, dealing [300 - 450] Lightning damage and makes enemies Vulnerable for 4 seconds.\n\nIf you recall no Storm Feathers, spawn 10 around you." },
    { name: "Aspect of Retribution", classes: [], power: "Distant enemies have a 20% chance to be Stunned for 2 seconds when they hit you. You deal [15 - 25]%[x] increased damage to Distant enemies." },
    { name: "Aspect of Shielding Bones", classes: ["necromancer"], power: "Casting a Bone Skill grants 2 stacks of Resolve. Gain [20 - 30]%[+] increased All Resistances while you have Resolve." },
    { name: "Aspect of Shredding Blades", classes: ["sorcerer"], power: "Conjuration damage makes enemies Vulnerable for 4 seconds. You deal [15.0 - 20.0]%[x] increased damage to Vulnerable enemies." },
    { name: "Aspect of Soil Power", classes: ["spiritborn"], power: "Lucky Hit: Up to a 25%[+] chance to create a Mystic Circle for 10 seconds.\n\nCasting a Centipede Skill in Mystic Circles empowers them to periodically apply [300 - 450] Poisoning damage over 6 seconds to enemies within while extending any Crowd Controls affecting them." },
    { name: "Aspect of Tenacity", classes: ["spiritborn"], power: "You gain Resolve for each [25 - 15] Vigor you gain while at Maximum Vigor. This can overfill your Resolve by 5 stacks." },
    { name: "Aspect of Transfusion", classes: ["necromancer"], power: "Lucky Hit: Blood Skills have up to a [30 - 50]% chance to create a Blood Orb at the target's location." },
    { name: "Aspect of Turbulence", classes: ["spiritborn"], power: "Soar casts Vortex at its landing location and deals [25 - 45]%[x] increased damage." },
    { name: "Aspect of Valiance", classes: ["paladin"], power: "Valor Skills generate [1 - 6] Resolve when cast." },
    { name: "Aspect of Warmth", classes: ["barbarian", "sorcerer"], power: "Each Nearby Burning enemy Heals you for [2.0 - 3.0]% of your Maximum Life every second." },
    { name: "Aspect of the Cursed Aura", classes: ["necromancer"], power: "A dark aura surrounds you, inflicting Decrepify and Iron Maiden on enemies who touch it.\n\nCurses inflicted this way spread to surrounding targets every [2.5 - 4] seconds and last 4 seconds outside of the aura." },
    { name: "Aspect of the Dark Howl", classes: ["druid"], power: "Debilitating Roar is now a Werewolf Skill. In addition, Debilitating Roar will Immobilize Poisoned enemies for [2.5 - 4.5] seconds." },
    { name: "Aspect of the Disciple", classes: ["paladin"], power: "Your Disciple skills now Weaken enemies for 8 seconds. You take [10 - 15]% reduced damage from Weakened enemies." },
    { name: "Aspect of the Embalmer", classes: ["necromancer"], power: "Consuming a Corpse has a 25% chance to spawn a Blood Orb. Blood Orb Healing is increased by [30 - 45]%." },
    { name: "Aspect of the Enchanter", classes: ["sorcerer"], power: "You gain [15.0 - 20.0]% Enchantment Potency." },
    { name: "Aspect of the Light's Mending", classes: ["paladin"], power: "Consuming Judgement Heals [2.5 - 3.5]% of your Maximum Life to you and Nearby Allies." },
    { name: "Aspect of the Northern Guard", classes: ["necromancer", "paladin", "spiritborn"], power: "Blocks have a [25 - 45]% chance to Freeze the attacker for 3 seconds." },
    { name: "Aspect of the Shapeshifter", classes: ["druid"], power: "Your form bonuses are maintained and you deal [12.0 - 18.0]% increased damage for 4 seconds when shapeshifting into a different form." },
    { name: "Aspect of the Ursine Horror", classes: ["druid"], power: "While in Werebear form, you receive 15% additional Healing from all sources. In addition, every [4.0 - 2.0] seconds, gain 1 stack of Overpower." },
    { name: "Aspect of the Void", classes: ["necromancer"], power: "Darkness Skills Weaken enemies for 4 seconds. Darkness Skills deal [10 - 15]%[x] increased damage to Weakened enemies." },
    { name: "Bane-Link Aspect", classes: ["warlock"], power: "Hexed enemies are Slowed by [50 - 70]% for 3 seconds when you make them Vulnerable or become Vulnerable for 3 seconds when you Slow them." },
    { name: "Battle Fervor's Aspect", classes: ["barbarian"], power: "Brawling Skills grant Berserking for 5 seconds on their first hit. Gain [10.0 - 15.0]% Damage Reduction while Berserking." },
    { name: "Battle-Mad Aspect", classes: ["barbarian"], power: "After swapping weapons 5 times gain Berserking for 4 seconds. Additionally, you deal [15.0 - 20.0]%[x] increased damage while Berserking." },
    { name: "Blast-Trapper's Aspect (Utility)", classes: ["rogue"], power: "Lucky Hit: Dealing damage to enemies affected by your Trap Skills has a [15 - 35]% chance to cause an explosion that deals [75 - 105] Shadow damage and applies Vulnerable for 4 seconds." },
    { name: "Blood Boiling Aspect", classes: [], power: "Every 6 seconds, gain 1 stack of Overpower. Gaining Overpower spawns 1 Volatile Blood Drop, and collecting it causes it to explode, dealing [675 - 974] Physical damage around you." },
    { name: "Blood Getter's Aspect", classes: ["necromancer"], power: "Your Skeletal Priests now also empower you at [55 - 75]% effectiveness." },
    { name: "Coldbringer's Aspect", classes: ["necromancer"], power: "Every 4 seconds, your Skeletal Mages cast a blizzard that deals [135 - 180] Cold damage and continuously Chills enemies for 6% over 8 seconds." },
    { name: "Earthstriker's Aspect", classes: ["barbarian", "rogue"], power: "Gain 1 Overpower stack each time you swap weapons. You deal [15.5 - 20.5]%[x] increased damage while you have Overpower." },
    { name: "Eluding Aspect", classes: [], power: "Becoming Crowd Controlled while Injured grants you Unstoppable for 4 seconds. This effect has a [6 - 4] second Cooldown." },
    { name: "Embattled Aspect", classes: ["barbarian", "druid", "necromancer", "paladin", "rogue", "warlock"], power: "Fortify's Drain Rate is increased by [100 - 150]%[+]." },
    { name: "Enfeebling Aspect", classes: ["warlock"], power: "Making an enemy Vulnerable has a [20 - 40]% chance to also Weaken them for 3 seconds." },
    { name: "Exploiter's Aspect", classes: [], power: "You have 50%[+] increased Crowd Control Duration. While enemies are Unstoppable, you deal [30 - 50]%[x] increased damage to them." },
    { name: "Fell Soothsayer's Aspect", classes: ["spiritborn"], power: "When you cast an Incarnate Skill enemies around you become Vulnerable for 5 seconds. Killing a Vulnerable enemy echoes [70 - 100]% of the killing blow's damage to another Nearby enemy." },
    { name: "Gorefeast Aspect", classes: ["warlock"], power: "If you have Eviscerated an enemy in the last 10 seconds, you gain [30 - 50]%[+] increased Fortify and it refills your Life 200%[+] faster." },
    { name: "Great Storm Aspect", classes: ["druid", "sorcerer", "spiritborn"], power: "Lucky Hit: Lightning damage has up to a 15% chance to grant a stack of Ferocity.\n\nYou gain [10.0 - 15.0]% Damage Reduction while you have Ferocity." },
    { name: "Hulking Aspect", classes: ["necromancer"], power: "Your Golem has a [2 - 18]% chance to reduce its active Cooldown by 2 seconds and a [1.0 - 9.0]% chance to spawn a Corpse each time it damages an enemy with its normal attack." },
    { name: "Icy Alchemist's Aspect", classes: ["rogue"], power: "Lucky Hit: Shadow damage has up to a 75% chance to release an explosion that deals 150 Cold damage to the target and surrounding enemies, Chilling for 25% and Weakening them for [3.0 - 6.0] seconds." },
    { name: "Impairing Aspect", classes: ["rogue"], power: "Lucky Hit: Marksman Skills have up to a 40% chance to deal [20 - 30]%[x] increased damage and Immobilize an enemy for 2 seconds." },
    { name: "Infiltrator's Aspect", classes: ["rogue"], power: "Poison Trap has no arm time, and no longer breaks Stealth and triggers no Cooldown while you are in Stealth. All Poison Traps activate when you exit Stealth and begin Poison Trap's Cooldown. Poison Trap's Cooldown is reduced by [10.0 - 50.0]%." },
    { name: "Lord of Blood's Aspect", classes: ["paladin"], power: "Lucky Hit: Zealot Skills have up to a 20% chance to heal you for [4.0 - 6.0]% of your missing Life." },
    { name: "Luckbringer Aspect", classes: ["barbarian"], power: "Gain [10 - 30]%[+] increased Lucky Hit Chance while all damage bonuses from the Walking Arsenal Key Passive are active." },
    { name: "Menacing Aspect", classes: ["spiritborn"], power: "Scourge continuously affects enemies around you for [5.0 - 9.0] seconds." },
    { name: "Mired Sharpshooter's Aspect", classes: ["rogue"], power: "Caltrops is now also a Marksman Skill that also throws [5 - 25] piercing daggers over its duration, each dealing 15 Shadow damage and applying Vulnerable for 3 seconds." },
    { name: "Necrotic Carapace Aspect", classes: ["necromancer"], power: "When a Corpse is formed from your Skills or your Minions, Fortify for [5 - 7]% of your Maximum Life." },
    { name: "Nefarious Aspect", classes: ["warlock"], power: "Becoming Crowd Controlled while you have Shadowform will consume a stack to apply it back to the attacker and adapt Shadowform to grant immunity to that type of effect for the next [4.0 - 8.0] seconds." },
    { name: "Overcharged Aspect", classes: ["druid"], power: "Your Storm Skill damage makes enemies Vulnerable for 4 seconds. You deal [15.0 - 20.0]%[x] increased damage to Vulnerable enemies." },
    { name: "Overheating Aspect", classes: ["barbarian", "sorcerer"], power: "Slain Burning enemies have a 10% chance to grant Overpower. Your Fire damage is increased by [15.0 - 20.0]%[x]." },
    { name: "Prepared Assailant's Aspect", classes: ["rogue"], power: "Breaking Stealth grants 4 Resolve. Gain an additional [20 - 30]%[+] Armor while you have Resolve." },
    { name: "Pyroclastic Aspect", classes: ["warlock"], power: "Brimstone explosions are 50% larger and deal [10 - 15]%[x] increased damage. Brimstones instantly detonate when you run over them in Demonform." },
    { name: "Raid Leader's Aspect", classes: ["barbarian"], power: "Your Shouts also Heal allies for [4.0 - 6.0]%[x] of their Maximum Life per second." },
    { name: "Raider's Aspect", classes: ["spiritborn"], power: "Heal for [10 - 15]% Maximum Life when you Poison a Healthy enemy." },
    { name: "Raw Might Aspect", classes: ["druid"], power: "Your Werebear Skill damage Stuns enemies for [2.0 - 3.0] seconds. Enemies can be Stunned this way every 5 seconds." },
    { name: "Sadistic Aspect", classes: ["warlock"], power: "When killing your Demons, you have a [30 - 50]% chance for each to count as two kills." },
    { name: "Shifter's Aspect", classes: ["druid"], power: "Your form bonuses are increased by [60 - 80]%[x]." },
    { name: "Steadfast Berserker's Aspect", classes: ["barbarian", "druid"], power: "Gain [4.0 - 6.0]% of your Maximum Life as Fortify whenever you deal direct damage while Berserking." },
    { name: "Sticker-thought Aspect", classes: ["barbarian", "druid", "necromancer", "paladin", "rogue", "sorcerer", "warlock"], power: "Gain [1,813 - 5,439] Thorns while Channeling and for 3 seconds afterwards." },
    { name: "Undying Aspect", classes: [], power: "Casting a Skill Heals you for [2.0 - 3.0]% of your Maximum Life. Double this bonus while Injured." },
    { name: "Weapon Master's Aspect", classes: ["barbarian"], power: "Weapon Mastery Skills Stun enemies for [1.0 - 1.5] seconds. Enemies can be Stunned this way once every 5 seconds. Your Weapon Mastery Skills have an additional Charge and deal [10 - 15]%[x] increased damage." },
    { name: "Wildbolt Aspect", classes: [], power: "Every [3.5 - 1.5] seconds, Distant enemies are Pulled In to you and take 15%[x] increased damage from you for 3 seconds. This effect cannot occur while you are in Stealth." },
    { name: "Wyward's Aspect", classes: ["druid", "sorcerer", "spiritborn"], power: "Lucky Hit: Lightning Damage has up to a [25 - 35]% chance to Stun enemies for 1.5 seconds." },
    { name: "of Siphoning Strikes Aspect", classes: ["rogue"], power: "Lucky Hit: Cutthroat Skills have up to a [45 - 65]% chance to Heal you for 3% of your Maximum Life." },
]);