// ══════════════════════════════════════════════════════════════
//  aspects-utility.js  —  Utility Legendary Aspects
// ══════════════════════════════════════════════════════════════
registerAspectCategory("utility", [
    // ── General ───────────────────────────────────────────
    { name: "Aspect of Anemia",                         slots: [] },
    { name: "Aspect of Control",                        slots: [] },
    { name: "Aspect of Encircling Blades",              slots: [] },
    { name: "Aspect of Explosive Verve",                slots: [] },
    { name: "Aspect of Grasping Veins",                 slots: [] },
    { name: "Aspect of Metamorphic Stone",              slots: [] },
    { name: "Aspect of Noxious Ice",                    slots: [] },
    { name: "Aspect of Piercing Cold",                  slots: [] },
    { name: "Aspect of Plunging Darkness",              slots: [] },
    { name: "Aspect of Retribution",                    slots: [] },
    { name: "Aspect of Singed Extremities",             slots: [] },
    { name: "Aspect of Stolen Vigor",                   slots: [] },
    { name: "Aspect of the Bounding Conduit",           slots: [] },
    { name: "Aspect of the Calm Breeze",                slots: [] },
    { name: "Aspect of the Caged Heart",                slots: [] },
    { name: "Aspect of the Changeling's Debt",          slots: [] },
    { name: "Aspect of the Damned",                     slots: [] },
    { name: "Aspect of the Frozen Tundra",              slots: [] },
    { name: "Aspect of the Protector",                  slots: [] },
    { name: "Aspect of the Rampaging Werebeast",        slots: [] },
    { name: "Aspect of the Relentless Armsmaster",      slots: [] },
    { name: "Aspect of the Ursine Horror",              slots: [] },
    { name: "Aspect of Three Curses",                   slots: [] },
    { name: "Aspect of Unstable Imbuements",            slots: [] },
    { name: "Bold Chieftain's Aspect",                  slots: [] },
    { name: "Cheat's Aspect",                           slots: [] },
    { name: "Earthstriker's Aspect",                    slots: [] },
    { name: "Exploiter's Aspect",                       slots: [] },
    { name: "Flamethrower's Aspect",                    slots: [] },
    { name: "Healer's Aspect",                          slots: [] },
    { name: "Nighthowler's Aspect",                     slots: [] },
    { name: "Protecting Aspect",                        slots: [] },
    { name: "Smiting Aspect",                           slots: [] },
    { name: "Stormchaser's Aspect",                     slots: [] },
    { name: "Unyielding Commander's Aspect",            slots: [] },
    { name: "Warding Key Aspect",                       slots: [] },
    // ── Barbarian ─────────────────────────────────────────
    { name: "Aspect of Ancestral Force",                slots: [] },
    { name: "Aspect of Berserk Ripping",                slots: [] },
    { name: "Aspect of Fierce Winds",                   slots: [] },
    { name: "Slaughterhouse Aspect",                    slots: [] },
    // ── Druid ─────────────────────────────────────────────
    { name: "Aspect of Armageddon",                     slots: [] },
    { name: "Aspect of Cyclonic Force",                 slots: [] },
    { name: "Aspect of Mending Stone",                  slots: [] },
    { name: "Aspect of Quicksand",                      slots: [] },
    { name: "Stormclaw's Aspect",                       slots: [] },
    { name: "Tempest Roar Aspect",                      slots: [] },
    // ── Necromancer ───────────────────────────────────────
    { name: "Aspect of Hardened Bones",                 slots: [] },
    { name: "Aspect of Reanimation",                    slots: [] },
    { name: "Aspect of the Void",                       slots: [] },
    { name: "Blood-bathed Aspect",                      slots: [] },
    { name: "Hulking Aspect",                           slots: [] },
    { name: "Sacrificial Aspect",                       slots: [] },
    // ── Rogue ─────────────────────────────────────────────
    { name: "Aspect of Arrow Storms",                   slots: [] },
    { name: "Aspect of Lethal Dusk",                    slots: [] },
    { name: "Aspect of Surprise",                       slots: [] },
    { name: "Aspect of Volatile Shadows",               slots: [] },
    { name: "Bladedancer's Aspect",                     slots: [] },
    // ── Sorcerer ──────────────────────────────────────────
    { name: "Aspect of Overwhelming Currents",          slots: [] },
    { name: "Aspect of Shielding Storm",                slots: [] },
    { name: "Aspect of Splintering Energy",             slots: [] },
    { name: "Aspect of Static Cling",                   slots: [] },
    { name: "Incendiary Aspect",                        slots: [] },
    // ── Spiritborn ────────────────────────────────────────
    { name: "Aspect of Alpha",                          slots: [] },
    { name: "Aspect of Celerity",                       slots: [] },
    { name: "Aspect of Earthen Devastation",            slots: [] },
    { name: "Aspect of Piercing Strikes",               slots: [] },
    { name: "Aspect of Ravaging Strikes",               slots: [] },
    { name: "Aspect of Shattering Blows",               slots: [] },
    { name: "Aspect of Unstable Verdungo",              slots: [] },
    // ── Paladin ───────────────────────────────────────────
    { name: "Aspect of Divine Retribution",             slots: [] },
    { name: "Aspect of Holy Consecration",              slots: [] },
    { name: "Aspect of Sacred Might",                   slots: [] },
    // ── Warlock ───────────────────────────────────────────
    { name: "Aspect of Cursed Strikes",                 slots: [] },
    { name: "Aspect of Dark Pacts",                     slots: [] },
    { name: "Aspect of Vile Torment",                   slots: [] }
]);
